name: Calculadora
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
  
    - name: Checkout do código
      uses: actions/checkout@v4

u
    - name: Verificar arquivos
      run: |
        echo "Monitorando o código do Eduardo..."
        ls -la
